# Generated by Django 4.1.7 on 2023-10-24 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=100)),
                ("dish_des", models.TextField(blank=True, null=True)),
                ("dish_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dish_img", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ord_number", models.CharField(max_length=20, unique=True)),
                ("ord_time", models.CharField(max_length=50)),
                ("ord_condition", models.CharField(default="默认状态", max_length=50)),
                (
                    "ord_money",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ord_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=100)),
                ("shop_number", models.CharField(max_length=20, unique=True)),
                ("shop_tel", models.CharField(max_length=20)),
                ("shop_head", models.CharField(max_length=50)),
                ("shop_pass", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OrderList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordlist_num", models.PositiveIntegerField()),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.dish",
                    ),
                ),
                (
                    "ord_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.order",
                        to_field="ord_number",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="ord_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=20)),
                ("emp_number", models.CharField(max_length=20)),
                ("emp_tel", models.CharField(max_length=20)),
                ("emp_conditon", models.CharField(max_length=20)),
                ("emp_role", models.CharField(default="普通员工", max_length=50)),
                (
                    "emp_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="dish_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
            ),
        ),
    ]
