# Generated by Django 4.1.7 on 2023-11-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ord_customer",
            new_name="cus_id",
        ),
    ]
