# Generated by Django 4.1.7 on 2024-03-11 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0003_rename_emp_conditon_employee_emp_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_cus",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
