# Generated by Django 4.1.7 on 2024-03-11 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0005_alter_shop_shop_cus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="shop_cus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
