# Generated by Django 4.1.7 on 2023-12-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotions",
            name="promo_des",
        ),
        migrations.RemoveField(
            model_name="promotions",
            name="shop_id",
        ),
        migrations.AddField(
            model_name="promotions",
            name="promo_code",
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="promotions",
            name="promo_multiple",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
