# Generated by Django 4.1.7 on 2023-11-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paycard",
            name="ord_number",
        ),
        migrations.AddField(
            model_name="paycard",
            name="card_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
