# Generated by Django 4.1.7 on 2023-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_paycard_card_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="usertype",
            field=models.CharField(default="customer", max_length=10),
        ),
    ]
