# Generated by Django 4.1.7 on 2023-12-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_customer_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paycard",
            name="card_condition",
            field=models.CharField(default="未激活", max_length=20),
        ),
    ]
